[package]
name = "aga8eos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "aga8eos"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.3"
aga8 = "0.4.0"